### PR TITLE
Added experimental compatibility for Linux. Twitter API Key use from …

### PR DESCRIPTION
**Pull request by zywek123**
Experimental compatibility for Linux.
Program runs, but Account settings not works yet.
I've used an API key from Mac.
Directory structures also from there, but some work is required to have fully access to this application from the first start, e.g. Linux does not know where to find external player, Two lines and will be done.
So, sounds are not playing now.
I've used accessibleOutputs2 from my repository, because i added compatibility with speech dispatcher instead of espeak, because espeak modules is not available in python 3.
Some work is required to have an access to the invisible interface by the shortcuts, which cannot be registered on Linux, probably i should modify KeyboardHandler from AccessibleApps.
I added an icon, it is an image where QuinterTray is written at the center of the image, because gtk don't want to spawn an interface without the icon, now on deprecated methods, but i will fix it today to get rid of errors.
In future, I want to add internationalization support via gettext, but maybe not now.
What do You think about this? WIll it be accepted on mainline branch or I have to merge mainline branches to my forked code?

### CODE REVIEW

**Comment by trypsynth** [comment]
Hi,
Thanks so much for this! This was something Mason tried to do but ran into a lot of issues, like you're saying, with sound, speech, etc. I might wait until a few of those issues are fixed, but I'll definatly merge it! I'll probably also generate another API key, but maybe not?
Also, regarding your AO2 fork: Did you put it in the repo, or redirect the requirements file?

**Comment by trypsynth** [comment]
Sorry I forgot to address this in my first comment, but localization would also be great. I honestly just didn't want to go through all 3000 lines of code to find all the strings to translate. If you're willing to though, by all means! :)

**Comment by zywek123** [comment]
Yep, i put ao2 in my repo. Today I'll try to fix not working sound and these thinks which I mentioned first, so probably I will submit a new PR, Or, unfortunately i don't know, if can i add more commits to this PR it will be good. And ofcourse modify requirements.txt to get AO2 from my repo, and modify KeyboardHandler i I will know how and what to fix.

**Comment by trypsynth** [comment]
If you push more commits to the branch you used to compare with this PR, it'll just let you push more commits. :). Figured that's what you wanted to do, which is why I didn't merge it yet. I can if you want though.

**Comment by zywek123** [comment]
I've fixed sounds on Linux, but if you have working that, you should replace /usr/lib/python3xx/site_packages/sound_lib/ with this found in my repository. Unfortunately i can't fix global shortcuts in invisible interface yet.
And, i'm  not sure how necessary are my contributions, because somebody said, that developmend of quinter is ending. I don't know, but working.

**Comment by zywek123** [comment]
I don't know, how necessary is my contribution, because i've found an information that development of this program is ending. What about that?

**Comment by trypsynth** [comment]
All that means is I'll no longer be writing code. I'm still willing to merge and such things. This code, as you probably know, is super messy though, which is a big reason it died.

**Pull request closed without merging**
