### PR TITLE
    Fixed the calculation method of the number of characters when composing a tweet #2

### PR DESCRIPTION
**Pull request by riku22**
Fix issue # 2.

### CODE REVIEW

**Comment by trypsynth** [comment]
Hi,
Looks pretty good, but I noticed you removed event from TweetGui.maximum, when WX passes it. Is there a reason for this, and will it still run?

**Comment by trypsynth** [comment]
I would also say this is worthy of listing in the changelog for the next version. Can you do this please?

**Comment by riku22** [comment]
>Looks pretty good, but I noticed you removed event from TweetGui.maximum, when WX passes it. Is there a reason for this, and will it still run?

The text Maximum setting isn't very useful, so I changed it to play the sound during the calculation.

>I would also say this is worthy of listing in the changelog for the next version. Can you do this please?

Done.

**Comment by trypsynth** [comment]
It seems TweetGui.chars is never reached. This allows you to type way more text in the field than the limit. Is it maybe possible to make this work  with wx.TextCtrl.SetMaxLength?

**Comment by trypsynth** [comment]
OK actually, I'm having some issues. Trying to fix them. Module object is not callable.

**Comment by trypsynth** [comment]
OK, all fixed. :). Thanks for your contribution!

**Pull request merged**
